#[cfg(test)]
mod tests {
    use soroban_sdk::{
        testutils::{Address as _, Events},
        token, Address, Bytes, Env, IntoVal,
    };

    // Import the contract and its client generated by soroban-sdk macros.
    use crate::{StellarPassContract, StellarPassContractClient, TicketError};

    // -----------------------------------------------------------------------
    // Helper: build a dummy Bytes value from a static byte slice.
    // -----------------------------------------------------------------------
    fn make_bytes(env: &Env, data: &[u8]) -> Bytes {
        Bytes::from_slice(env, data)
    }

    // -----------------------------------------------------------------------
    // TEST 1 — Happy path
    //
    // A ticket is successfully registered on-chain and the organizer wallet
    // receives an XLM payout representing ticket-sale settlement.
    //
    // Steps:
    //   1. Deploy the StellarPass contract.
    //   2. Deploy a mock XLM token contract and mint funds to the payer.
    //   3. Call register_ticket() → expect Ok(()).
    //   4. Call payout_organizer() → expect Ok(()).
    //   5. Assert the organizer's token balance increased by the expected amount.
    // -----------------------------------------------------------------------
    #[test]
    fn test_happy_path_register_and_payout() {
        let env = Env::default();
        env.mock_all_auths(); // auto-approve all require_auth calls in this test

        // Deploy StellarPass contract.
        let contract_id = env.register_contract(None, StellarPassContract);
        let client = StellarPassContractClient::new(&env, &contract_id);

        // Create participant addresses.
        let organizer = Address::generate(&env);
        let payer = Address::generate(&env);

        // Deploy a mock fungible token to simulate XLM.
        let xlm_token_id = env.register_stellar_asset_contract_v2(payer.clone());
        let xlm_token_address = xlm_token_id.address();
        let token_admin_client =
            token::StellarAssetClient::new(&env, &xlm_token_address);
        // Mint 1 000 XLM (in stroops: 1 XLM = 10_000_000 stroops) to payer.
        token_admin_client.mint(&payer, &10_000_000_000_i128);

        // --- register_ticket -----------------------------------------------
        let ticket_hash = make_bytes(&env, b"TICKET_HASH_001_CONCERT_2025");
        let event_hash  = make_bytes(&env, b"EVENT_HASH_MANILA_ARENA_2025");
        let price       = 5_000_000_i128; // 0.5 XLM in stroops

        let reg_result = client.try_register_ticket(
            &ticket_hash,
            &organizer,
            &event_hash,
            &price,
        );
        assert!(
            reg_result.is_ok(),
            "Happy-path registration should succeed"
        );

        // --- payout_organizer ----------------------------------------------
        let payout_amount = 5_000_000_i128;
        let payout_result = client.try_payout_organizer(
            &xlm_token_address,
            &payer,
            &organizer,
            &payout_amount,
        );
        assert!(
            payout_result.is_ok(),
            "Organizer payout should succeed after valid registration"
        );

        // Verify the organizer actually received the XLM.
        let token_client = token::Client::new(&env, &xlm_token_address);
        let organizer_balance = token_client.balance(&organizer);
        assert_eq!(
            organizer_balance, payout_amount,
            "Organizer balance should equal the payout amount"
        );
    }

    // -----------------------------------------------------------------------
    // TEST 2 — Edge case: duplicate ticket registration is rejected
    //
    // Registering the same ticket_hash twice must return
    // TicketError::AlreadyRegistered on the second call.
    //
    // This prevents scalpers or bad actors from issuing duplicate passes for
    // the same slot.
    // -----------------------------------------------------------------------
    #[test]
    fn test_duplicate_registration_rejected() {
        let env = Env::default();
        env.mock_all_auths();

        let contract_id = env.register_contract(None, StellarPassContract);
        let client = StellarPassContractClient::new(&env, &contract_id);

        let owner       = Address::generate(&env);
        let ticket_hash = make_bytes(&env, b"DUPLICATE_TICKET_HASH_XYZ");
        let event_hash  = make_bytes(&env, b"EVENT_HASH_CEBU_EXPO_2025");
        let price       = 2_000_000_i128;

        // First registration — must succeed.
        let first = client.try_register_ticket(&ticket_hash, &owner, &event_hash, &price);
        assert!(first.is_ok(), "First registration should succeed");

        // Second registration with the same hash — must fail.
        let second = client.try_register_ticket(&ticket_hash, &owner, &event_hash, &price);
        assert!(
            second.is_err(),
            "Second registration with the same hash should be rejected"
        );

        // Confirm the error is exactly AlreadyRegistered (code 1).
        let err = second.unwrap_err().unwrap();
        assert_eq!(
            err,
            soroban_sdk::Error::from_contract_error(TicketError::AlreadyRegistered as u32),
            "Error code should be AlreadyRegistered"
        );
    }

    // -----------------------------------------------------------------------
    // TEST 3 — State verification
    //
    // After a successful registration, the on-chain storage must correctly
    // reflect the ticket owner address and event hash.  Also confirms that
    // verify_ticket() marks the ticket as used and that a second scan attempt
    // returns AlreadyUsed.
    //
    // This directly tests the tamper-detection and duplicate-scan-prevention
    // logic that is core to StellarPass's anti-fraud guarantee.
    // -----------------------------------------------------------------------
    #[test]
    fn test_storage_state_after_registration_and_verify() {
        let env = Env::default();
        env.mock_all_auths();

        let contract_id = env.register_contract(None, StellarPassContract);
        let client = StellarPassContractClient::new(&env, &contract_id);

        let owner       = Address::generate(&env);
        let ticket_hash = make_bytes(&env, b"STATE_CHECK_TICKET_HASH_001");
        let event_hash  = make_bytes(&env, b"STATE_CHECK_EVENT_HASH_001");
        let price       = 3_000_000_i128;

        // Register the ticket.
        client.register_ticket(&ticket_hash, &owner, &event_hash, &price);

        // --- Verify stored record ------------------------------------------
        let record = client.get_ticket(&ticket_hash);
        assert_eq!(record.owner,      owner,      "Stored owner must match");
        assert_eq!(record.event_hash, event_hash, "Stored event_hash must match");
        assert_eq!(record.price_stroops, price,   "Stored price must match");

        // Ticket should not be marked used yet.
        assert!(
            !client.is_used(&ticket_hash),
            "Ticket should be unused before first scan"
        );

        // --- First scan (valid) -------------------------------------------
        let verify_result = client.try_verify_ticket(&ticket_hash, &event_hash);
        assert!(
            verify_result.is_ok(),
            "First valid scan should succeed"
        );
        assert!(
            client.is_used(&ticket_hash),
            "Ticket should be marked used after first scan"
        );

        // --- Second scan (duplicate — must be rejected) -------------------
        let second_scan = client.try_verify_ticket(&ticket_hash, &event_hash);
        assert!(
            second_scan.is_err(),
            "Second scan of same ticket should be rejected"
        );
        let err = second_scan.unwrap_err().unwrap();
        assert_eq!(
            err,
            soroban_sdk::Error::from_contract_error(TicketError::AlreadyUsed as u32),
            "Error code should be AlreadyUsed"
        );
    }
}
